OOP school library: add basic UI
Mikey1-nuel/school_library pull request #4
Opened 2023-06-29 11:15 UTC by Mikey1-nuel

## OOP school library: add basic UI

**In this project I:**

- Created a `app.rb` file that will serve as your console app entry-point. It should have methods that do the following:
  - List all books.
  - List all people.
  - Created a person (teacher or student, not a plain `Person`).
  - Created a book.
  - Created a rental.
  - List all rentals for a given person id.
- In your `main.rb` define the entry point, this will be a method called `main` that is invoked at the end of your file. This method should do the following:
  - Present the user with a list of options to perform.
  - Lets users choose an option.
  - If needed, ask for parameters for the option.
  - Have a way to quit the app.

2023-06-29 12:03 UTC, franclobo requested changes
Hi @Mikey1-nuel, 

# ♻️ Required Changes ♻️

![so-close-jim-halpert](https://github.com/Mikey1-nuel/school_library/assets/58642949/20b2ed70-6deb-41ef-9910-6e57e0b376cb)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- No linter errors ✔️ 
- Descriptive PR ✔️ 
- Correct Git flow ✔️ 
- Good UI ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

- There are some little issues to be fixed for the correct functionality of your app.

- [ ] **In person.rb** Please 🙏🏽 remove false from the method `can_use_services?` otherwise it will return false always 👇🏽 

``` ruby
 def can_use_services?
    of_age? || @parent_permission
  end 
```

- [ ] **In class student and class teacher** Add the argument name to the super to avoid the issue `unknown keyword: :name (ArgumentError)` to be able to create student and teacher.

``` ruby
def initialize(age, parent_permission: true, name: 'Unknown')
    super(age, name, parent_permission: parent_permission)
  end
```

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-29 18:56 UTC, franclobo reviewed
Hi @Mikey1-nuel, 

# Invalid Code Review Request ❌ 

![descarga](https://github.com/Mikey1-nuel/school_library/assets/58642949/e24c32b4-af44-4d91-9b8f-f376c44464c6)

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has linter errors ❌ 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-29 20:49 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi @Mikey1-nuel 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, I really appreciate the effort you put in! but there are still some which haven't been addressed yet.

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## Highlights 🌟

- ✔️ Descriptions are very descriptive
- ✔️ Linters checks are passing
- ✔️ Build interactive console apps.
- ✔️ Run a program using the command line.

## Required Changes ♻️
_Please kindly check the comments under the review._

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-29 20:49 UTC, abdulhamiid commented on main.rb
> +end
Example video
![image](https://github.com/Mikey1-nuel/school_library/assets/78251927/42602977-1063-4e2a-9b0d-334bb2d5e285)

Your app console
![image](https://github.com/Mikey1-nuel/school_library/assets/78251927/dcae89a8-49de-4063-83c7-0a17f5711308)

According to the project requirements, our console app should behave in the same way as it is in the example. 🤗

Please implement the following to make your app behave in the same way as the [example video](https://www.youtube.com/watch?v=vkkgrhD6aXQ)

- 👀 `Has parent permission?` is not required to create a `Teacher`. 🤓 please remove it 👍
- Kindly add a success message that will be displayed when a new item is created. e.g `Person created successfully`

2023-06-29 20:49 UTC, abdulhamiid commented on app.rb
> +  end
Your app console
![image](https://github.com/Mikey1-nuel/school_library/assets/78251927/2dc5e605-f339-4ddf-8033-aee3f00657aa)

Currently, the method `def create_rental` is not working, and creating a rental crash in the app, please kindly fix this issue to ensure that the console app works as expected.. 💪☺

2023-06-30 23:36 UTC, KanzaTahreem requested changes
# Changes Required 🔁

Hi @Mikey1-nuel 🙋‍♀️

Good job so far! I really appreciate the effort you put in!  **_However, there are few this that still need to be fixed. But you are almost there!_** 💪 🏁

![so close](https://media.tenor.com/3sCHnD_x2RIAAAAC/almost-there.gif)


## Highlights 🎯

There are some excellent points that you have made perfectly. Keep up the great work! 👏
- ✅ Good job with the UI
- ✅ Descriptive PR
- ✅ Correct Linters

## Required Changes 🛑

_Please check the comments under the review._

## Optional suggestions ❕


N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-30 23:36 UTC, KanzaTahreem commented on app.rb
> +  end
- [ ] Well done so far 🥇 The message "Choose an existing option!" is a part of the error handling in the `run_app` and `run_app2` methods. In the `display_options` method, there are two separate calls to `run_app` and `run_app2`, which can lead to the "Choose an existing option!" message appearing even when a valid option is selected ⚠ This was not the case in the last review. Kindly fix this to make sure that your app behave in the same way as the [example video](https://www.youtube.com/watch?v=vkkgrhD6aXQ) according to the project requirements as mentioned earlier and avoiding any confusion for the user 😃

 ![image](https://github.com/Mikey1-nuel/school_library/assets/106119105/513d0363-f2f8-4978-897b-aea910608bcc)

2023-07-01 18:13 UTC, Ghiftee approved these changes
## STATUS: APPROVED ♻️♻️
Hi @Mikey1-nuel, 

To highlight 👍🏽 
✔️ App runs as expected
✔️ App matches wireframe

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀  
Congratulations! 🎉 

![](https://camo.githubusercontent.com/f181708ef1a4a773db8464e77479f28ed4dae506d4d8da5c19f44c8e00d31232/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f594b646d3931584f4e4c5461772f67697068792d646f776e73697a65642d6d656469756d2e676966)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-01 21:58 UTC, merged